apiVersion: v1
kind: Service
metadata:
  name: grafana-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host }}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana